require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShippersController do

  # This should return the minimal set of attributes required to create a valid
  # Shipper. As you add validations to Shipper, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "company_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShippersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all shippers as @shippers" do
      shipper = Shipper.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shippers).should eq([shipper])
    end
  end

  describe "GET show" do
    it "assigns the requested shipper as @shipper" do
      shipper = Shipper.create! valid_attributes
      get :show, {:id => shipper.to_param}, valid_session
      assigns(:shipper).should eq(shipper)
    end
  end

  describe "GET new" do
    it "assigns a new shipper as @shipper" do
      get :new, {}, valid_session
      assigns(:shipper).should be_a_new(Shipper)
    end
  end

  describe "GET edit" do
    it "assigns the requested shipper as @shipper" do
      shipper = Shipper.create! valid_attributes
      get :edit, {:id => shipper.to_param}, valid_session
      assigns(:shipper).should eq(shipper)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shipper" do
        expect {
          post :create, {:shipper => valid_attributes}, valid_session
        }.to change(Shipper, :count).by(1)
      end

      it "assigns a newly created shipper as @shipper" do
        post :create, {:shipper => valid_attributes}, valid_session
        assigns(:shipper).should be_a(Shipper)
        assigns(:shipper).should be_persisted
      end

      it "redirects to the created shipper" do
        post :create, {:shipper => valid_attributes}, valid_session
        response.should redirect_to(Shipper.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shipper as @shipper" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shipper.any_instance.stub(:save).and_return(false)
        post :create, {:shipper => { "company_name" => "invalid value" }}, valid_session
        assigns(:shipper).should be_a_new(Shipper)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shipper.any_instance.stub(:save).and_return(false)
        post :create, {:shipper => { "company_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shipper" do
        shipper = Shipper.create! valid_attributes
        # Assuming there are no other shippers in the database, this
        # specifies that the Shipper created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shipper.any_instance.should_receive(:update).with({ "company_name" => "MyString" })
        put :update, {:id => shipper.to_param, :shipper => { "company_name" => "MyString" }}, valid_session
      end

      it "assigns the requested shipper as @shipper" do
        shipper = Shipper.create! valid_attributes
        put :update, {:id => shipper.to_param, :shipper => valid_attributes}, valid_session
        assigns(:shipper).should eq(shipper)
      end

      it "redirects to the shipper" do
        shipper = Shipper.create! valid_attributes
        put :update, {:id => shipper.to_param, :shipper => valid_attributes}, valid_session
        response.should redirect_to(shipper)
      end
    end

    describe "with invalid params" do
      it "assigns the shipper as @shipper" do
        shipper = Shipper.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shipper.any_instance.stub(:save).and_return(false)
        put :update, {:id => shipper.to_param, :shipper => { "company_name" => "invalid value" }}, valid_session
        assigns(:shipper).should eq(shipper)
      end

      it "re-renders the 'edit' template" do
        shipper = Shipper.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shipper.any_instance.stub(:save).and_return(false)
        put :update, {:id => shipper.to_param, :shipper => { "company_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shipper" do
      shipper = Shipper.create! valid_attributes
      expect {
        delete :destroy, {:id => shipper.to_param}, valid_session
      }.to change(Shipper, :count).by(-1)
    end

    it "redirects to the shippers list" do
      shipper = Shipper.create! valid_attributes
      delete :destroy, {:id => shipper.to_param}, valid_session
      response.should redirect_to(shippers_url)
    end
  end

end
