require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ViewedprosController do

  # This should return the minimal set of attributes required to create a valid
  # Viewedpro. As you add validations to Viewedpro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ViewedprosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all viewedpros as @viewedpros" do
      viewedpro = Viewedpro.create! valid_attributes
      get :index, {}, valid_session
      assigns(:viewedpros).should eq([viewedpro])
    end
  end

  describe "GET show" do
    it "assigns the requested viewedpro as @viewedpro" do
      viewedpro = Viewedpro.create! valid_attributes
      get :show, {:id => viewedpro.to_param}, valid_session
      assigns(:viewedpro).should eq(viewedpro)
    end
  end

  describe "GET new" do
    it "assigns a new viewedpro as @viewedpro" do
      get :new, {}, valid_session
      assigns(:viewedpro).should be_a_new(Viewedpro)
    end
  end

  describe "GET edit" do
    it "assigns the requested viewedpro as @viewedpro" do
      viewedpro = Viewedpro.create! valid_attributes
      get :edit, {:id => viewedpro.to_param}, valid_session
      assigns(:viewedpro).should eq(viewedpro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Viewedpro" do
        expect {
          post :create, {:viewedpro => valid_attributes}, valid_session
        }.to change(Viewedpro, :count).by(1)
      end

      it "assigns a newly created viewedpro as @viewedpro" do
        post :create, {:viewedpro => valid_attributes}, valid_session
        assigns(:viewedpro).should be_a(Viewedpro)
        assigns(:viewedpro).should be_persisted
      end

      it "redirects to the created viewedpro" do
        post :create, {:viewedpro => valid_attributes}, valid_session
        response.should redirect_to(Viewedpro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved viewedpro as @viewedpro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Viewedpro.any_instance.stub(:save).and_return(false)
        post :create, {:viewedpro => { "user_id" => "invalid value" }}, valid_session
        assigns(:viewedpro).should be_a_new(Viewedpro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Viewedpro.any_instance.stub(:save).and_return(false)
        post :create, {:viewedpro => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested viewedpro" do
        viewedpro = Viewedpro.create! valid_attributes
        # Assuming there are no other viewedpros in the database, this
        # specifies that the Viewedpro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Viewedpro.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => viewedpro.to_param, :viewedpro => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested viewedpro as @viewedpro" do
        viewedpro = Viewedpro.create! valid_attributes
        put :update, {:id => viewedpro.to_param, :viewedpro => valid_attributes}, valid_session
        assigns(:viewedpro).should eq(viewedpro)
      end

      it "redirects to the viewedpro" do
        viewedpro = Viewedpro.create! valid_attributes
        put :update, {:id => viewedpro.to_param, :viewedpro => valid_attributes}, valid_session
        response.should redirect_to(viewedpro)
      end
    end

    describe "with invalid params" do
      it "assigns the viewedpro as @viewedpro" do
        viewedpro = Viewedpro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Viewedpro.any_instance.stub(:save).and_return(false)
        put :update, {:id => viewedpro.to_param, :viewedpro => { "user_id" => "invalid value" }}, valid_session
        assigns(:viewedpro).should eq(viewedpro)
      end

      it "re-renders the 'edit' template" do
        viewedpro = Viewedpro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Viewedpro.any_instance.stub(:save).and_return(false)
        put :update, {:id => viewedpro.to_param, :viewedpro => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested viewedpro" do
      viewedpro = Viewedpro.create! valid_attributes
      expect {
        delete :destroy, {:id => viewedpro.to_param}, valid_session
      }.to change(Viewedpro, :count).by(-1)
    end

    it "redirects to the viewedpros list" do
      viewedpro = Viewedpro.create! valid_attributes
      delete :destroy, {:id => viewedpro.to_param}, valid_session
      response.should redirect_to(viewedpros_url)
    end
  end

end
